### incorrect email field
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "id": 2,
  "age": 20,
  "name": "X",
  "email": "email@emil.com"
}

### incorrect age field
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "age": -1,
  "name": "X",
  "email": "email@emil.com"
}