spring:
  application:
    name: interceptor

  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

webservice:
  connectTimeout: 5
  readTimeout: 5

  client:
    url: ${HTTP_JSON_PLACEHOLDER_URL:https://jsonplaceholder.typicode.com}
    path:
      posts:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_POSTS:posts}
      comments:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_COMMENTS:comments}

  internal:
    url: http://localhost:8080
    path:
      posts:
        findAll: /api/posts/internal

logging:
  level:
    web: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE