### yyyy-MM-dd
POST http://localhost:8080/v1/events/date?
    date=2024-09-03


### Custom DateTime Format: dd.mm.yyyy
POST http://localhost:8080/v1/events/customDateTimeFormat?
    date=03.09.2023

###
POST http://localhost:8080/v1/events/local-date?
    localDate=2024-09-03

### yyyy-MM-dd HH:mm:ss
POST http://localhost:8080/v1/events/local-date-time?
    localDateTime=2024-09-03T21:15:00

### find all events
GET http://localhost:8080/v1/events

### create event
POST http://localhost:8080/v1/events
Content-Type: application/json

{
  "text": "Test event",
  "start": "2024-09-03T21:15:00",
  "end": "2024-09-03T21:15:00",
  "backColor": "red",
  "borderColor": "black"
}

### delete event by id
DELETE  http://localhost:8080/v1/events/1

###
PATCH http://localhost:8080/v1/events/3
Content-Type: application/json

{
  "start": "2024-09-03T21:15:00",
  "end": "2024-09-03T21:15:00"
}