###
GET http://localhost:8080/v1/events

### yyyy-MM-dd
POST http://localhost:8080/v1/events/date?
    date=2024-09-03

###
POST http://localhost:8080/v1/events/local-date?
    localDate=2024-09-03

### yyyy-MM-dd HH:mm:ss
POST http://localhost:8080/v1/events/local-date-time?
    localDateTime=2024-09-03T21:15:00

###
DELETE  http://localhost:8080/v1/events/1


###
PATCH http://localhost:8080/v1/events/3
Content-Type: application/json

{
  "start": "2024-09-03T21:15:00",
  "end": "2024-09-03T21:15:00"
}