spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: leaky_bucket_with_bucket4j_and_redis

  threads:
    virtual:
      enabled: true

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  username: ${REDIS_USERNAME:none}
  password: ${REDIS_PASSWORD:none}

token:
  bucket:
    capacity: 1
    refill:
      tokens: 1
      period: 3